# Generated by Django 6.0.3 on 2026-03-20 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
